export const Schemas = {
  agency: "Agency",
  city: "City",
  company: "Company",
  client: "Client",
  credential: "Credential",
  employee: "Employee",
  employeeRating: "EmployeeRating",
  hub: "Hub",
  merchant: "Merchant",
  ride: "Ride",
  salary: "Salary",
  shipment: "Shipment",
  vehicle: "Vehicle",
};
