export { default } from "./default.service.js";

export { default as agencyService } from "./agency.service.js";
export { default as cityService } from "./city.service.js";
export { default as clientService } from "./client.service.js";
export { default as companyService } from "./company.service.js";
export { default as authenticationService } from "./authentication.service.js";
export { default as employeeService } from "./employee.service.js";
export { default as employeeRatingService } from "./employeeRating.service.js";
export { default as hubService } from "./hub.service.js";
export { default as rideService } from "./ride.service.js";
export { default as salaryService } from "./salary.service.js";
export { default as shipmentService } from "./Shipment/shipment.service.js";
export { default as createShipmentService } from "./Shipment/createShipment.service.js";
export { default as vehicleService } from "./vehicle.service.js";
export { default as rideTemplateService } from "./rideTemplate.service.js";
export { default as deliveryReceiptService } from "./DeliveryReceipt/deliveryReceipt.service.js";
export { default as confirmDeliveryReceiptService } from "./DeliveryReceipt/confirmDeliveryReceipt.service.js";
export { default as createDeliveryReceiptService } from "./DeliveryReceipt/createDeliveryReceipt.service.js";
export { default as completeShipmentService } from "./Shipment/completeShipment.service.js";
