export * as authService from "./auth.service";
export * as citiesService from "./cities.service";
export * as ordersService from "./orders.service";
export * as organizationsService from "./organizations.service";
export * as productsService from "./products.service";
export * as ridesService from "./rides.service";
export * as rolesService from "./roles.service";
export * as usersService from "./users.service";
export * as vehiclesService from "./vehicles.service";
